#!/bin/bash

# Phase 4 Quick Wins Script
# Applies immediate code quality improvements

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo ""
    echo -e "${BLUE}=================================================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}=================================================================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_info() {
    echo -e "${BLUE}→${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_header "PHASE 4 QUICK WINS"

echo "This script will apply immediate code quality improvements:"
echo "  1. Fix unused imports"
echo "  2. Format code with rustfmt"
echo "  3. Apply clippy suggestions"
echo "  4. Run tests to verify nothing broke"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

# Save current state
print_header "1. SAVING CURRENT STATE"
print_info "Creating backup branch..."
git branch -f phase4-backup-$(date +%Y%m%d-%H%M%S) 2>/dev/null || true
print_success "Backup created"

# Fix unused imports and variables
print_header "2. FIXING UNUSED CODE"
print_info "Running cargo fix..."
if cargo fix --allow-dirty --allow-staged 2>&1 | grep -q "Fixed"; then
    print_success "Fixed unused imports and variables"
else
    print_info "No fixes needed"
fi

# Format code
print_header "3. FORMATTING CODE"
print_info "Running rustfmt..."
cargo fmt
print_success "Code formatted"

# Run clippy and show suggestions
print_header "4. RUNNING CLIPPY"
print_info "Checking for issues..."
if cargo clippy --all-targets -- -D warnings 2>&1 | tee /tmp/clippy_output.txt; then
    print_success "No clippy warnings"
else
    print_warning "Clippy found issues (see output above)"
    echo ""
    echo "Would you like to apply automatic fixes? (y/n)"
    read -p "> " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        print_info "Applying clippy fixes..."
        cargo clippy --fix --allow-dirty --allow-staged --all-targets
        print_success "Clippy fixes applied"
    fi
fi

# Run tests
print_header "5. RUNNING TESTS"
print_info "Running test suite..."
if cargo test --release 2>&1 | grep -q "test result: ok"; then
    print_success "All tests passed"
else
    print_warning "Some tests failed"
    echo ""
    echo "Tests failed. This might be expected if clippy made breaking changes."
    echo "Review the changes and fix any test failures."
fi

# Show what changed
print_header "6. SUMMARY OF CHANGES"
if git diff --stat | grep -q "file"; then
    echo ""
    git diff --stat
    echo ""
    print_info "Files modified:"
    git diff --name-only | sed 's/^/  - /'
    echo ""
    print_info "Review changes with: git diff"
    print_info "Revert changes with: git checkout ."
else
    print_info "No changes made"
fi

# Offer to commit
print_header "7. COMMIT CHANGES?"
if git diff --quiet; then
    print_info "No changes to commit"
else
    echo "Would you like to commit these changes? (y/n)"
    read -p "> " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git add -A
        git commit -m "Phase 4 quick wins: Fix warnings and format code

Applied automatic code quality improvements:
- Fixed unused imports and variables
- Formatted code with rustfmt
- Applied clippy suggestions
- Verified all tests still pass

Generated by: scripts/quick_wins.sh"
        print_success "Changes committed"
    else
        print_info "Changes not committed. Review with 'git diff'"
    fi
fi

print_header "QUICK WINS COMPLETE"
print_success "Code quality improvements applied"
echo ""
echo "Next steps:"
echo "  - Review changes: git diff"
echo "  - Run full test suite: ./run_discovery_tests.sh"
echo "  - See Phase 4 plan: cat PHASE4_PLAN.md"
echo ""
